version: '1'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: simple_ecommerce_database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    env_file: .env
    container_name: simple_ecommerce_backend
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            gunicorn simple_ecommerce.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - postgres
