version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: simple_ecommerce_database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: .
    env_file: .env
    container_name: simple_ecommerce_backend
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            gunicorn simple_ecommerce.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - mysql

volumes:
  mysql_data:
