# Generated by Django 4.1 on 2024-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/products/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/products/'),
        ),
    ]
