# Generated by Django 4.1 on 2024-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_label',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', max_length=15),
        ),
    ]
