# Generated by Django 4.1 on 2024-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_address_delivery_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='shipping', max_length=15),
        ),
    ]
