# Generated by Django 4.1 on 2024-01-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_billing_address_and_more'),
        ('checkout', '0004_alter_checkout_billing_address_and_more'),
        ('user', '0011_alter_address_address_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
