import Image from 'next/image'
import './globals.css'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/navigation'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Simple E-commerce',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-white `}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    )
}
