import Image from 'next/image'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white` }>
        <nav className='flex p-8 fixed'>
          <Image src='/logo.svg' width={160} height={90} alt='logo' />
          Header
        </nav>
        {children}
      </body>
    </html>
  )
}
