# Generated by Django 4.1 on 2024-01-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_checkout_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='total_amount_currency',
        ),
    ]
